accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls

app_name = 'accounts'

urlpatterns = [
    path('singup/' , views.sing_up , name='singup'),
    path('profile/' , views.profile_information , name='profile'),
    path('profile/edit/' , views.edit_profile , name='edit_profile'),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.home_list , name='home_list' ),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path # iam import include

# my basic includ code from django decomention
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.urls

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    #my code
    path('jobs/', include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact'))

]

# my basic includ code from django decomention
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from location_field.models.plain import PlainLocationField
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    birthday = models.DateField(blank=True, null=True , help_text='Example : 2002-12-29' )
    city = models.CharField(max_length=255,blank=True, null=True)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    address = models.CharField(max_length=100,blank=True, null=True)
    address_more = models.CharField(max_length=100, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True , help_text='Example : +20 the number')
    fax_number = PhoneNumberField(blank=True, null=True , help_text='Example : +20 the number')
    image = models.ImageField(upload_to='profile_im/', blank=True, null=True)
    
    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
#craete by me

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SingUp(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2',]
        
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

class UserProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user','location')

accounts/views.py
from django.shortcuts import redirect, render

# Create your views here.
from .models import Profile
from .forms import SingUp, UserForm , UserProfile
from django.contrib.auth import authenticate, login
from datetime import datetime
from django.contrib.auth.decorators import login_required

def sing_up(request):
    if request.method == 'POST':
        form = SingUp(request.POST , request.FILES)
        if form.is_valid:
            form.save()
            user = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(user=user,password=password)
            login(request,user)
            return redirect('/accounts/profile/edit/')
    else:
        form = SingUp()
    context = {'form':form}
    return render(request,'accounts/singup.html',context)

@login_required
def profile_information(request):
    profile_info = Profile.objects.get(user=request.user)
    context = {'profile':profile_info}
    return render(request,'accounts/profile.html',context)

@login_required
def edit_profile(request):
    profile_info = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form1 = UserForm(request.POST , request.FILES , instance=request.user) 
        form2 = UserProfile(request.POST , request.FILES , instance=profile_info)
        if form1.is_valid and form2.is_valid:
            form1.save()
            myform2 = form2.save(commit=False)
            myform2.user = request.user
            myform2.save()
            return redirect('/accounts/profile')
    else:
        form1 = UserForm(instance=request.user) 
        form2 = UserProfile(instance=profile_info)
    context = {'user':form1 , 'profile':form2 }
    return render(request,'accounts/edit_Profile.html',context)

accounts/templates/accounts/edit_Profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
Edit Profile
{% endblock title %}

{% block body %}
<section class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto">
          <div class="bg-light p-3 border rounded mb-4">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3" style="text-align: center;" >Edit Profile</h3>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form user %}
    {% bootstrap_form profile %}
    <input type="submit" value="Save" class="btn btn-primary border-width-2 d-none d-lg-inline-block col-lg-12" />
    </form>
    </div>
</div>
</div>
</div>
</section>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
{{profile.user.first_name}} {{profile.user.last_name}} Profile
{% endblock title %}


{% block body %}

<section class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto">
          <div class="bg-light p-3 border rounded mb-4">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3" style="text-align: center;" >Profile Information</h3>
            <ul class="list-unstyled pl-3 mb-0">
              <li class="mb-2 ml-5 "><div class="ml-5" ><div class="ml-5" ><div class="ml-3" ><img style="width:170px;height:170px;" class="ml-5" src='{{profile.image.url}}'></div></div></div></li>              
              <li class="mb-2"><strong class="text-black">Username : </strong>{{profile.user.username}}</li>
              <li class="mb-2"><strong class="text-black">First Name : </strong>{{profile.user.first_name}}</li>
              <li class="mb-2"><strong class="text-black">Last Name : </strong>{{profile.user.last_name}}</li>
              <li class="mb-2"><strong class="text-black">Email : </strong>{{profile.user.email}}</li>
              <li class="mb-2"><strong class="text-black">Date of Birth : </strong>{{profile.birthday}}</li>
              <li class="mb-2"><strong class="text-black">city : </strong>{{profile.city}}</li>
              <li class="mb-2"><strong class="text-black">Address : </strong>{{profile.address}}</li>
              <li class="mb-2"><strong class="text-black">Detalis Address : </strong>{{profile.address_more}}</li>
              <li class="mb-2"><strong class="text-black">Phone Number : </strong>{{profile.phone_number}}</li>
              <li class="mb-2"><strong class="text-black">Fax Number : </strong>{{profile.fax_number}}</li>
              <li class="mb-2"><strong class="text-black">Joined At : </strong>{{profile.user.date_joined|date:'d M o'}}</li>
            </ul>
            
          </div>
          <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block col-lg-12" >Edit Profile</a>
        </div>
      </div>
    </div>
  </section>


{% endblock body %}

accounts/templates/accounts/singup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
Sing Up
{% endblock title %}

{% block body %}
<div class="w-50" style="margin: auto; margin-top:20px" >
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Sing Up" class="btn btn-primary border-width-2 d-none d-lg-inline-block" />
    </form>
    <p><a class="btn btn-primary border-width-2 d-none d-lg-inline-block" style="margin-top: 20px;" href="{% url 'login' %}">If You Have An Account "Log In"</a></p>
</div>
{% endblock %}