accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls

app_name = 'accounts'

urlpatterns = [
    path('singup/' , views.sing_up , name='singup'),
    path('profile/' , views.profile_information , name='profile'),
    path('profile/edit/' , views.edit_profile , name='edit_profile'),
]

contact/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'contact'

urlpatterns = [
    path('', views.send_email , name='contact' ),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.home_list , name='home_list' ),
]

jobs/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list , name='job_list' ),
    path('jobs/<str:slug>/<int:id>', views.job_detail , name='job_detail' ),
    path('jobs/<str:slug>/<int:id>/apply', views.applyForm , name='applyForm' ),
    path('post/', views.addJob , name='addJob' ),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path # iam import include

# my basic includ code from django decomention
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.urls

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    #my code
    path('jobs/', include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact'))

]

# my basic includ code from django decomention
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">

<head>
  <title>Careers &mdash; Website Template by Colorlib</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body id="top">


  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->


    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="site-logo col-6"><a href="{% url 'home:home_list' %}">Careers</a></div>

          <nav class="mx-auto site-navigation">
            <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
              <li><a href="{% url 'home:home_list' %}" class="nav-link">Home</a></li>
              <li><a href="{% url 'jobs:job_list' %}" class="nav-link">Job Listings</a></li>
              <li class=""><a href="{% url 'contact:contact' %}">Contact Us</a></li>
              <li class=""><a href="{% url 'jobs:addJob' %}">Post Job</a></li>
              <li class=""><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </nav>
          
          {% if request.user.is_authenticated %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto">
              <a href="{% url 'accounts:profile' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                  class="mr-2 icon-paper-plane"></span>Profile</a>
            </div>
          </div> 
          {% else %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto">
              <a href="{% url 'login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                  class="mr-2 icon-paper-plane"></span>Login</a>
            </div>
          </div>
          {% endif %}


        </div>
      </div>
    </header>
    
        <!-- HOME -->
        <section class="home-section section-hero inner-page overlay bg-image" style="background-image: url({% static 'images/hero_1.jpg' %});"
        id="home-section">
  
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-12">
                <div class="col-md-7">
                  <h1 class="text-white font-weight-bold">{% block title %}{% endblock title %}</h1>
                </div>
            </div>
          </div>
        </div>
      </section>

{% block body %}
  
{% endblock body %}

  

<section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-8">
        <h2 class="text-white">Looking For A Job?</h2>
        <p class="mb-0 text-white lead">Lorem ipsum dolor sit amet consectetur adipisicing elit tempora adipisci
          impedit.</p>
      </div>
      <div class="col-md-3 ml-auto">
        <a href="{% url 'accounts:singup' %}" class="btn btn-warning btn-block btn-lg">Sign Up</a>
      </div>
    </div>
  </div>
</section>

    <footer class="site-footer">
        <div class="container">
          <div class="row mb-5">
            <div class="col-6 col-md-3 mb-4 mb-md-0">
              <h3>Search Trending</h3>
              <ul class="list-unstyled">
                <li><a href="#">Web Design</a></li>
                <li><a href="#">Graphic Design</a></li>
                <li><a href="#">Web Developers</a></li>
                <li><a href="#">Python</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">CSS3</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
              <h3>Company</h3>
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Career</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Resources</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
              <h3>Support</h3>
              <ul class="list-unstyled">
                <li><a href="#">Support</a></li>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Terms of Service</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
              <h3>Contact Us</h3>
              <div class="footer-social">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-linkedin"></span></a>
              </div>
            </div>
          </div>
  
          <div class="row text-center">
            <div class="col-12">
              <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                with <i class="icon-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                  target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>
        </div>
      </footer>
  
    </div>
  
    <!-- SCRIPTS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/stickyfill.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  
    <!-- <script src="{% static 'js/bootstrap-select.min.js' %}"></script> -->
  
    <script src="{% static 'js/custom.js' %}"></script>
  
  
  </body>
  
  </html>