home/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.home_list , name='home_list' ),
]

jobs/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views 

app_name = 'jobs'

urlpatterns = [
    path('', views.job_list , name='job_list' ),
    path('jobs/<str:slug>/<int:id>', views.job_detail , name='job_detail' ),
    path('jobs/<str:slug>/<int:id>/apply', views.applyForm , name='applyForm' ),
    path('post/', views.addJob , name='addJob' ),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path # iam import include

# my basic includ code from django decomention
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.urls

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    #my code
    path('jobs/', include('jobs.urls',namespace='jobs')),
    path('',include('home.urls',namespace='home')),
    path('contact/',include('contact.urls',namespace='contact'))

]

# my basic includ code from django decomention
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
# Create your models here.
from django.template.defaultfilters import slugify
from django.utils.text import slugify
from django.contrib.auth.models import User
import random
from location_field.models.plain import PlainLocationField

JOB_TYPE = (
    ("Full Time","Full Time"),
    ("Part Time","Part Time"),
)

GENDER = (
    ("Male","Male"),
    ("Female","Female"),
    ("Any","Any"),
)

def images_upload(instance , filename):
    point = filename.find(".")
    end_image = filename[int(point):]
    list_id = []
    n = str(random.random())
    for num in list_id:
    	if n != num:
    		list_id.append(n)
    	else:
    		n = str(random.random())
    return "job/%s.%s"%(str(n[2:]) , end_image)
   
        
class job(models.Model):
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=50 , choices=JOB_TYPE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    country = models.CharField(max_length=255)
    location_country = PlainLocationField(based_fields=['country'], zoom=7, blank=True, null=True)
    city = models.CharField(max_length=255)
    location_city = PlainLocationField(based_fields=['city'], zoom=7, blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    low_salary = models.PositiveIntegerField(default=0)
    heigh_salary = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to=images_upload)
    vacancy = models.PositiveIntegerField(default=0)
    Experience = models.PositiveIntegerField(default=0)
    Gender = models.CharField(max_length=50 , choices=GENDER)
    Deadline = models.DateField(help_text='Example : 2002-12-29')
    description = models.TextField(max_length=2000)
    slug = models.SlugField(blank=True , null=True)
    
    def save(self , *args, **kwargs):
        self.slug = slugify(self.title)
        super(job,self).save(*args , **kwargs)
        
    def __str__(self):
        return self.title
    

class apply_job(models.Model):
    apply_by = models.ForeignKey(User,on_delete=models.CASCADE)
    apply_to = models.ForeignKey(job , related_name='apply_job' , on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    description = models.TextField(max_length=1000)
    create_at = models.DateTimeField()
    Experience = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.name

jobs/forms.py
from django import forms
from .models import apply_job,job

class apply(forms.ModelForm):
    class Meta:
        model = apply_job
        fields = ['name','email','cv','description','website','Experience',]
        
        
class AddJob(forms.ModelForm):
    class Meta:
        model = job
        fields = '__all__'
        exclude = ('created_by','location_city','location_country','created_at','slug',)
        

jobs/views.py
from django.shortcuts import get_object_or_404, redirect, render

# Create your views here.
from django.urls import reverse
from .models import job
from django.core.paginator import Paginator
from .forms import apply , AddJob
from datetime import datetime
from django.contrib.auth.decorators import login_required

def job_list(request):
    jobList = job.objects.all()
    paginator = Paginator(jobList, 7) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"jobs": jobList , 'job_l':page_obj}
    return render(request,'jobs/job_list.html',context)

def job_detail(request , id , slug):
    jobDetail = get_object_or_404(job , id=id , slug=slug)
    context = {'job':jobDetail}
    return render(request,'jobs/job_detail.html',context)

@login_required
def applyForm(request , id , slug):
    jobDetail = get_object_or_404(job , id=id , slug=slug)
    if request.method == 'POST':
        form = apply(request.POST , request.FILES)
        if form.is_valid:
            myform = form.save(commit=False)
            myform.apply_to = jobDetail
            myform.apply_by = request.user
            myform.create_at = datetime.now()
            myform.save()
    else:
            form = apply()
    context = {'job':jobDetail , 'form':form}
    return render(request,'jobs/apply_form.html',context)


def addJob(request):
    if request.method == 'POST':
        form = AddJob(request.POST , request.FILES)
        if form.is_valid:
            myform = form.save(commit=False)
            myform.created_by = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))    
    else:
        form = AddJob()
    context = {'form':form}
    return render(request,'jobs/postJob.html',context)

jobs/templates/jobs/apply_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
Apply for {{job.title}}
{% endblock title %}

{% block body %}
<div class="col-lg-8" style="margin: auto; margin-top:30px ">
<div class="apply_job_form white-bg">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button class="boxed-btn3 w-100 " style="color: white; background:#1747C3; " type="submit">Apply Now</button>
        {% endbuttons %}
    </form>
</div>
</div>
{% endblock body %}

jobs/templates/jobs/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
{{job.title}}
{% endblock title %}


{% block body %}

<section class="site-section">
    <div class="container">
      <div class="row align-items-center mb-5">
        <div class="col-lg-8 mb-4 mb-lg-0">
          <div class="d-flex align-items-center">
            <div class="border p-2 d-inline-block mr-3 rounded">
              <img style="margin:-15px;" width="82px" height="82px" src="{{job.image.url}}" alt="Free Website Template By Free-Template.co">
            </div>
            <div>
              <h2>{{job.title}}</h2>
              <div>
                <span class="m-2"><span class="icon-room mr-2"></span>{{job.city}}</span>
                <span class="m-2"><span class="icon-clock-o mr-2"></span><span class="text-primary">{{job.job_type}}</span></span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="row">
            <div class="col-6">
              <a href="{% url 'jobs:applyForm' job.slug job.id %}" class="btn btn-block btn-primary btn-md">Apply Now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="col-lg-8 descript_wrap white-bg">
            <div class="mb-5 single_wrap descript_wrap white-bg">
              <figure class="mb-5"></figure>
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-align-left mr-3"></span>Job
                Description</h3>
              <p>{{job.description}}</p>
            </div>
        
        </div>
        <div class="col-lg-4">
          <div class="bg-light p-3 border rounded mb-4">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
            <ul class="list-unstyled pl-3 mb-0">
              <li class="mb-2"><strong class="text-black">Published on:</strong> {{job.created_at|date:'d M o'}}</li>
              <li class="mb-2"><strong class="text-black">Vacancy:</strong> {{job.vacancy}}</li>
              <li class="mb-2"><strong class="text-black">Employment Status:</strong> {{job.job_type}}</li>
              <li class="mb-2"><strong class="text-black">Experience:</strong> {{job.Experience}} year(s)</li>
              <li class="mb-2"><strong class="text-black">Job Location:</strong> {{job.city}} City</li>
              <li class="mb-2"><strong class="text-black">Salary:</strong> ${{job.low_salary}}k - ${{job.heigh_salary}}k</li>
              <li class="mb-2"><strong class="text-black">Gender:</strong> {{job.Gender}}</li>
              <li class="mb-2"><strong class="text-black">Application Deadline:</strong> {{job.Deadline}}</li>
            </ul>
          </div>
  
          <div class="bg-light p-3 border rounded">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Share</h3>
            <div class="px-3">
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-facebook"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-twitter"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-linkedin"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-pinterest"></span></a>
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>


{% endblock body %}

jobs/templates/jobs/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
  Job Listings
{% endblock title %}
{% block body %}
 
<section class="site-section">
    <div class="container">

      <div class="row mb-5 justify-content-center">
        <div class="col-md-7 text-center">
          <h2 class="section-title mb-2">{{jobs.count}} Job Listed</h2>
        </div>
      </div>

      {% for jobs in job_l %}
        
      
    
      <div class="mb-5">
        <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
          <div class="col-md-2">
            <a href="{% url 'jobs:job_detail' jobs.slug jobs.id %}"><img src="{{jobs.image.url}}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-4">
            <span class="badge badge-primary px-2 py-1 mb-3">{{jobs.job_type}}</span>
            <h2><a href="{% url 'jobs:job_detail' jobs.slug jobs.id %}">{{jobs.title}}</a> </h2>
            <p class="meta">Publisher: <strong>{{jobs.created_by}}</strong> In: <strong>{{jobs.created_at|date:'d M o'}}</strong></p>
          </div>
          <div class="col-md-3 text-left">
            <h3>{{jobs.city}}</h3>
            <span class="meta">{{jobs.country}}</span>
          </div>
          <div class="col-md-3 text-md-right">
            <strong class="text-black">${{jobs.low_salary}}k &mdash; ${{jobs.heigh_salary}}k</strong>
          </div>
        </div>
      </div>

      {% endfor %}

      {% if job_l.has_other_pages %}

      <div class="row pagination-wrap">

        <div class="col-md-6 text-center text-md-left">
          <div class="custom-pagination ml-auto">

            {% if job_l.has_previous %}
            <a href="?page={{job_l.previous_page_number}}" class="prev">Previous</a>
            {% endif %}

            {% for i in job_l.paginator.page_range %}
            <div class="d-inline-block">
              {% if job_l.number == i %}
              <a href="?page={{i}}" class="active">{{i}}</a>
              {% else %}
              <a href="?page={{i}}">{{i}}</a>
              {% endif %}
            </div>
            {% endfor %}

            {% if job_l.has_next %}
            <a href="?page={{job_l.next_page_number}}" class="next">Next</a>
            {% endif %}

          </div>
        </div>
      </div>

      {% endif %}
    </div>
  </section>

{% endblock body %}

jobs/templates/jobs/postJob.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
Post Job
{% endblock title %}

{% block body %}
<div class="col-lg-8" style="margin: auto; margin-top:30px ">
<div class="apply_job_form white-bg">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button class="boxed-btn3 w-100 " style="color: white; background:#1747C3; " type="submit">Post Now</button>
        {% endbuttons %}
    </form>
</div>
</div>
{% endblock body %}